import JSEncrypt from "jsencrypt";
//公钥
// const PUBLIC_KEY = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC3+2kBT+EJq8PqSrleCgsddWtwuIDaNtSwWunuyaRuSGWhBJxFApWXv8xfdchhbw5ti/2z3w5ipAufXJ/5R9FwBGSGEivbpUUCpVuk7iFY8vE+yfZTobEkfJ0vsO9FllG9AofYDAP5dlKYfTnXpNv7HrPrZfleB5HOtXS1OMt02wIDAQAB';
const PRIVATE_KEY = `-----BEGIN PRIVATE KEY-----
MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEA014Knw/eBCMcMXTL
wOegJ34MRFgLpVVHmutiodvD3VOsjkZ8vo/BNuB0IIDao2Sr30q/qDyGEMFHVWIN
i+omOwIDAQABAkEAipxnVrxvGkN0H7K6U/0R+BQfM0qSCJCObrfibMbUAXXGx9bJ
rDl+CxX/aVhUtrq6WeSIb6Tkq+4GFPw4TEjoYQIhAO6ZZXHXVkQbt8xgfTNeRAys
Dh4ziN5Sj4JK9PpXx52zAiEA4sg7QFPLGb9kZXg6RkR5vLSDIVqCSRzNy40ZSGFu
4VkCIQCjozrK18fHUEc++RIE7+q10i6gkfGVoIPh9SyMoTU7NwIgYRu6e3YmDvVs
qSKNWY9yzYJCcGLQTTxfRx05SUwnbakCIC23K2uFC6WRI43Box6xgfQMpvg+r/jr
jkRavGc3LMS+
-----END PRIVATE KEY-----`;
//私钥
// const PRIVATE_KEY = 'MIICXAIBAAKBgQC3+2kBT+EJq8PqSrleCgsddWtwuIDaNtSwWunuyaRuSGWhBJxFApWXv8xfdchhbw5ti/2z3w5ipAufXJ/5R9FwBGSGEivbpUUCpVuk7iFY8vE+yfZTobEkfJ0vsO9FllG9AofYDAP5dlKYfTnXpNv7HrPrZfleB5HOtXS1OMt02wIDAQABAoGBALb3QIL8hGjQt+JNc7EwvcMLHdEYu5PHiZbkotZFE9BVETSjWCFNI6WpKT8Z7C/xeOC6opB52F2ClMhkHfeTU5SpQx2YoRXjQGxCigTaRvlMo2q8q05sy4cxKpE+7c4yMaZSPldrx5HjLLlJzso7xngtHqnP/wQsbNnARhQ31tIhAkEA58D7SxU0i8UWSR1hPrXC4iPfDXTwtFOVyyHWCCId5fNFH6omlyHzleH4WLSYe/ZBAJRpPUqUeLlSKtkzonIgsQJBAMs693OXOeQpZdWUFlEl0hvcQFclaSID2TPbcL/doMslYd7tegyhBIrQRIzUQooZF5lbcsBLwb1hFPx0N7E6MUsCQH6pIC5W9pL1MkrffchyOoKxrDSElxFXJWURpxJm4wRMQpkdu12aNrDSAZMpkLUfT0Nr2WCgJCkez+OPNgMwcOECQGlMMBHv9MrGuECk7bs1wVs2DxAYDhTVsaAwvoZqqnkW8VKz8FzCwLu7lQjyoVc0EQogW6BOoB8jQeBbxs9Iu2kCQAFzAhRnjj1Rn2uvMqRCva+ez3RPaLHK4BzC5UdgF/qTu58+K29UqKSLenMB8ZZ1VQIJ83VnKSiIyHqeHBjl6LE=';
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANNeCp8P3gQjHDF0y8DnoCd+DERYC6VV
R5rrYqHbw91TrI5GfL6PwTbgdCCA2qNkq99Kv6g8hhDBR1ViDYvqJjsCAwEAAQ==
-----END PUBLIC KEY-----`;
// 公钥加密
export function encrypt(str) {
  const encryptor = new JSEncrypt();
  encryptor.setPublicKey(PUBLIC_KEY);
  return encryptor.encrypt(str);
}
// 私钥解密
export function decrypt(str) {
  const encryptor = new JSEncrypt();
  encryptor.setPrivateKey(PRIVATE_KEY);
  return encryptor.decrypt(str);
}
